# Generated by Django 5.1.4 on 2025-05-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twd', '0014_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
